// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502065453_add seed data")]
    partial class addseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 5, 2, 9, 54, 51, 711, DateTimeKind.Local).AddTicks(5923),
                            Description = "Went Hiking with Joey",
                            Title = "Went Hiking"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 5, 2, 9, 54, 51, 711, DateTimeKind.Local).AddTicks(6605),
                            Description = "Went Hiking with Joey",
                            Title = "Went Hiking"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2025, 5, 2, 9, 54, 51, 711, DateTimeKind.Local).AddTicks(6608),
                            Description = "Went Hiking with Joey",
                            Title = "Went Hiking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
